Add resource for Carriages
zealot9000/railway-project pull request #1
Opened 2017-02-06 19:43 UTC by zealot9000

2017-02-07 17:51 UTC, psylone requested changes

2017-02-07 17:51 UTC, psylone commented on app/models/route.rb
> +  class Route < ActiveRecord::Base
О, эти пробелы явно лишние )

2017-02-07 17:51 UTC, psylone commented on app/views/carriages/show.html.erb
> +    <p>Carriage attach to train: <%= @carriage.train.number %></p>
`is attached` :)

2017-02-07 17:51 UTC, psylone commented on app/views/routes/show.html.erb
> +<%= render 'trains' %>
👍

2017-02-07 17:51 UTC, psylone commented on app/views/trains/show.html.erb
> +      <% @train.carriages.each do |car| %>
Это лучше вынести в паршиал.

2017-02-07 17:51 UTC, psylone commented on app/views/trains/show.html.erb
> +      <% @train.carriages.each do |car| %>
Вообще суть в том, что требуется отображать **количество** вагонов и мест различных типов.

2017-02-07 17:51 UTC, psylone commented on db/migrate/20170206175425_create_carriages.rb
> +      t.integer :top_seats
Здесь по дефолту будет удобно задать значение `0`.

2017-02-07 17:51 UTC, psylone commented on db/migrate/20170206175425_create_carriages.rb
> +      t.string :type_w
Лучше назвать это поле просто `type`. На самом деле оно имеет особое значение и дальше мы это увидим в ходе курса.

Также не повредит какая-то проверка на допустимые типы вагонов. Ведь это поле является строкой и фактически мы можем ввести что-угодно.

2017-02-08 18:54 UTC, zealot9000 commented on db/migrate/20170206175425_create_carriages.rb
> +      t.string :type_w
Column name 'type' is restricted in ActiveRecord. Такие дела

2017-02-09 00:30 UTC, psylone commented on db/migrate/20170206175425_create_carriages.rb
> +      t.string :type_w
Да, это верно, это поле понадобится далее. Сейчас можно использовать метод класса:

```ruby
self.inheritance_column = nil
```

2017-02-09 23:33 UTC, psylone approved these changes

2017-02-09 23:33 UTC, psylone commented on db/migrate/20170208193315_change_column_default.rb
> +    change_column_default :carriages, :top_seats, 0
👍

2017-02-09 23:33 UTC, psylone commented on app/views/trains/show.html.erb
> +  <strong> Number of carriages:</strong> <%= @train.carriages.count %>
По заданию требовалось выводить количество вагонов по типам.

2017-02-09 23:33 UTC, psylone commented on app/views/trains/show.html.erb
> +  <%= render 'carriage' %>
Лучше назвать паршиал `carriages`, либо здесь проверять наличие вагонов и рендерить коллекцию:

```html
<ul>
  <% if @train.carriages.present? %>
    <%= render partial: 'carriage', collection: @train.carriages %>
  <% else %>
      This train has no carriages.
  <% end %>
</ul>
```

2017-02-11 10:45 UTC, merged