Callbacks
zealot9000/railway-project pull request #2
Opened 2017-02-13 20:08 UTC by zealot9000

2017-02-13 22:43 UTC, psylone requested changes
Проверь пожалуйста как сортируются станции при выводе информации о конкретном маршруте.

2017-02-13 22:43 UTC, psylone commented on db/migrate/20170212173930_add_index_station_to_railway_stations_routes.rb
> +    add_column :railway_stations_routes, :index_station, :integer
Упустил где используется это поле.

2017-02-13 22:43 UTC, psylone commented on app/views/routes/show.html.erb
> +<%= render 'station' %>
Если рендерим коллекцию, логичней назвать `stations`.

2017-02-13 22:43 UTC, psylone commented on db/schema.rb
> +    t.integer  "sitting_seats"
Здесь тоже нужны значения по умолчанию.

2017-02-13 22:43 UTC, psylone commented on app/models/carriage.rb
> +  scope :ordered, ->(order) { order(number: order ? 'asc' : 'desc') }
Если передавать `'asc'` или `'desc'` сразу, можно измежать тернарки.

2017-02-13 22:43 UTC, psylone commented on app/models/carriage.rb
> +  scope :total_side_bottom, -> { sum(:side_bottom_seats) }
Вообще говоря, скоупы в основном нужны чтобы получать срезы данных по различным условиям. Предполагается что они возвращают релейшен и их можно сцеплать друг с другом. Я понимаю твою идею, однако будет лучше сделать методы `sum` не скоупами, а методами класса:

```ruby
def self.total_top
  sum(:top_seats)
end
```

Это тоже будет работать. Кроме того, можно передавать параметр в метод и считать то что нужно:

```ruby
def self.total_seats(type)
  sum(type)
end
```

2017-02-13 22:43 UTC, psylone commented on app/models/carriage.rb
> +  scope :comfortable,       -> { where(type: 'ComfortableCarriage') }
Здесь всё хорошо, но можно ещё вынести все возможные варианты типов вагонов в константу `TYPES` и потом написать так:

```ruby
TYPES.each do |type|
  scope type, -> { where(type: type) }
end
```

Также можно использовать константу для валидации `inclusion in`. Так мы получим только одно место куда нужно добавить новый тип вагона.

2017-02-13 22:43 UTC, psylone commented on app/models/carriage.rb
> +    self.number = train.carriages.size + 1
Можно работать с полем `train_id` непосредственно, так как сам объект Поезда здесь нам не нужен.

2017-02-13 22:43 UTC, psylone commented on app/views/carriages/_form.html.erb
> +  <%= f.select :type, ['ComfortableCarriage', 'CoupeCarriage', 'EconomyCarriage', 'SittingCarriage'] %>
Вот тут наша константа `Carriage::TYPES` тоже бы пригодилась.

2017-02-13 22:43 UTC, psylone commented on app/views/carriages/show.html.erb
> +  <% if @carriage.type.eql?('ComfortableCarriage') %>
Это хороший ход! Можно ещё так:

```html
<%= render @carriage.type.underscore, carriage: @carriage %>
```

2017-02-13 22:43 UTC, psylone commented on app/views/trains/_carriages.html.erb
> +  <li>
Это бы тоже по паршиалам разнести.

2017-02-13 22:43 UTC, psylone commented on db/schema.rb
> +    t.boolean  "queue",              default: true
Молодец что сделал значение по умолчанию!

2017-02-15 18:38 UTC, zealot9000 commented on db/migrate/20170212173930_add_index_station_to_railway_stations_routes.rb
> +    add_column :railway_stations_routes, :index_station, :integer
Кажется это поле было добавлено в рамках эксперимента. Не могу восстановить по памяти какого )

2017-02-15 18:39 UTC, zealot9000 commented on app/models/carriage.rb
> +    self.number = train.carriages.size + 1
Не очень понял в каком виде можно использовать train_id

2017-02-16 14:50 UTC, psylone commented on app/models/carriage.rb
> +    self.number = train.carriages.size + 1
`Carriage.where(train_id: self.train_id).count + 1`.

2017-02-16 14:59 UTC, psylone commented on app/models/carriage.rb
> +    scope k.to_sym, -> { where(type: v) }
Не нужно `to_sym` здесь.

2017-02-16 14:59 UTC, psylone commented on app/models/carriage.rb
> +  TYPES.each do |k, v|
Для хэша лучше использовать `each_pair` и в блок передавать более явные аргументы, например `type_name` и `type`.

2017-02-16 14:59 UTC, psylone commented on app/views/carriages/_form.html.erb
> +  <%= f.select :type, Carriage::TYPES.values %>
Ещё лучше сделать метод класса: `Carriage.types`.

2017-02-16 14:59 UTC, psylone commented on app/views/carriages/show.html.erb
> +    <%= render @carriage.type.downcase, carriage: @carriage %>
Да, да! Но `if` уже не нужен. В этом и смысл )

2017-02-16 14:59 UTC, psylone commented on db/migrate/20170212173930_add_index_station_to_railway_stations_routes.rb
> +    add_column :railway_stations_routes, :index_station, :integer
Может быть в рамках сортировки Станций при отображении Маршрута? )

2017-02-24 19:25 UTC, merged